### PR TITLE
Feature/currency spacing

### PR DESCRIPTION
**Pull request by mwoc**
How's this looking for adding currencySpacing support to renderCurrencyShort and renderCurrencyLong?

### CODE REVIEW

**Comment by papandreou** [comment]
Missing the cldr version bump to 3.2.0?

**Comment by papandreou** [comment]
LGTM otherwise.

**Comment by mwoc** [comment]
Woops, indeed had it npm link'ed in, fixed now

**Comment by papandreou** [comment]
Thanks, great work!

**Pull request merged**
